my_blog:
    resource: "@MyBlogBundle/Controller/"
    type:     annotation
    prefix:   /
blog:
    path:     "/blog/{id}"
    defaults: { _controller:MyBlogBundle:Blog:index, id: 'all'}
addblog:
    path:      "/addblog"
    defaults:  { _controller:MyBlogBundle:Blog:add }
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
